<?php
$holiday = array(
	'2019-1-1' => 'New Year\'s Day',
	'2019-2-5' => 'Chinnese Lunar New Year\'s Day',
	'2019-3-7' => 'Bali\'s Day of Silence and Hindu New Year',
	'2019-4-3' => 'Ascension of the Prophet Muhammad',
	'2019-4-17' => 'PEMILU',
	'2019-4-19' => 'Good Friday',
	'2019-5-1' => 'Buruh\'s Day',
	'2019-5-19' => 'Waisak Day (Buddha\'s Anniversary)',
	'2019-5-30' => 'Isa Almasih',
	'2019-6-1' => 'Pancasila Day',
	'2019-6-5' => 'Idul Fitri',
	'2019-8-12' => 'Eid al-al-Adha',
	'2019-8-17' => 'Indonesian Independen Day',
	'2019-9-1' => 'Muharram/Islamic New Year',
	'2019-11-9' => 'The Prophet Muhammad\'s Birthday',
	'2019-12-24' => 'Chrismas Eve',
	'2019-12-25' => 'Chrismas Day',);
?>
